# Generated by Django 4.0.6 on 2023-03-06 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UrlHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.URLField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('custom_addr', models.CharField(max_length=10, unique=True)),
                ('metrics', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='router.metrics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
