# Generated by Django 4.0.6 on 2023-03-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_remove_metrics_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
